apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
spec:
  selector:
    matchLabels:
      app: bookstore
      tier: frontend
  template:
    metadata:
      labels:
        app: bookstore
        tier: frontend
    spec:
      containers:
      - name: restapi
        image: hechen2/pybook
        env:
          - name: DB
            value: mongodb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restapi
spec:
  selector:
    app: bookstore
    tier: frontend
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: bookstore
      tier: backend
  template:
    metadata:
      labels:
        app: bookstore
        tier: backend
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: bookstore
    tier: backend
  ports:
  - port: 27017
    targetPort: 27017
